trigger:
  branches:
    include:
      - master

pool:
  vmImage: windows-latest

steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'specific'
      project: '2ec7d690-f151-4bef-a72c-9443ce41227a'
      pipeline: '4'
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'greenMarketArtifact'
      downloadPath: '$(Build.ArtifactsDirectory)'
  
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students(3825a1c0-e294-4a3a-9d64-47657021c39a)'
      appType: 'webApp'
      appName: 'GreenMarket'
      package: '$(Build.ArtifactsDirectory)/greenMarketArtifact/*.zip'
      deploymentMethod: 'auto'
