trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest' 

variables:
  buildConfiguration: "Release"
  solution: "**/GreenMarket.sln"
  project: "**/GreenMarket.csproj"

steps:
  - task: NuGetToolInstaller@1
    name: 'NugetInstall'
    
  - task: NuGetCommand@2
    name: 'NugetRestore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    name: 'BuildArtifact'
    inputs:
      command: 'publish'
      projects: '$(project)'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
  
  - task: PublishBuildArtifacts@1
    name: 'PublishArtifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'greenMarketArtifact'
      publishLocation: 'Container'